-- 테스트용 운동 종목 마스터 데이터.
-- training_name의 UNIQUE 제약을 기준으로 여러 번 실행해도 같은 행이 중복 생성되지 않는다.
INSERT INTO `training_category` (
    `training_name`,
    `training_display_name`,
    `training_type`,
    `target_category`,
    `target_muscle`
)
VALUES
    ('BENCHPRESS',        '벤치프레스',            'FREE_WEIGHT', 'UPPER', 'CHEST'),
    ('INCLINEBENCHPRESS', '인클라인 벤치프레스',   'FREE_WEIGHT', 'UPPER', 'CHEST'),
    ('DECLINEBENCHPRESS', '디클라인 벤치프레스',   'FREE_WEIGHT', 'UPPER', 'CHEST'),
    ('DUMBBELLFLY',       '덤벨 플라이',            'FREE_WEIGHT', 'UPPER', 'CHEST'),
    ('PECDECFLY',         '펙 덱 플라이',           'MACHINE',     'UPPER', 'CHEST'),
    ('CHESTPRESS',        '체스트프레스',           'MACHINE',     'UPPER', 'CHEST'),
    ('INCLINECHESTPRESS', '인클라인 체스트프레스', 'MACHINE',     'UPPER', 'CHEST'),
    ('CABLECROSSOVER',    '케이블 크로스오버',      'MACHINE',     'UPPER', 'CHEST'),
    ('OVERHEADPRESS',     '오버헤드 프레스',        'FREE_WEIGHT', 'UPPER', 'DELTOID'),
    ('LATERALRAISE',      '레터럴 레이즈',          'FREE_WEIGHT', 'UPPER', 'DELTOID'),
    ('FRONTRAISE',        '프론트 레이즈',          'FREE_WEIGHT', 'UPPER', 'DELTOID'),
    ('UPRIGHTROW',        '업라이트 로우',          'FREE_WEIGHT', 'UPPER', 'DELTOID'),
    ('SHOULDERPRESS',     '숄더프레스',             'MACHINE',     'UPPER', 'DELTOID'),
    ('REARDELTFLY',       '리어 델트 플라이',       'MACHINE',     'UPPER', 'DELTOID'),
    ('FACEPULL',          '페이스 풀',              'MACHINE',     'UPPER', 'DELTOID'),
    ('BARBELLROW',        '바벨 로우',              'FREE_WEIGHT', 'UPPER', 'UPPER_BACK'),
    ('ONEARMDUMBBELLROW', '원 암 덤벨 로우',        'FREE_WEIGHT', 'UPPER', 'UPPER_BACK'),
    ('TBARROW',           '티바 로우',              'FREE_WEIGHT', 'UPPER', 'UPPER_BACK'),
    ('LATPULLDOWN',       '랫 풀다운',              'MACHINE',     'UPPER', 'UPPER_BACK'),
    ('WIDEGRIPLATPULLDOWN','와이드 그립 랫 풀다운', 'MACHINE',     'UPPER', 'UPPER_BACK'),
    ('SEATEDROW',         '시티드 로우',            'MACHINE',     'UPPER', 'UPPER_BACK'),
    ('BACKEXTENSION',     '백 익스텐션',            'MACHINE',     'UPPER', 'LOWER_BACK'),
    ('BICEPSCURL',        '바이셉스 컬',            'FREE_WEIGHT', 'UPPER', 'BICEPS'),
    ('BARBELLCURL',       '바벨 컬',                'FREE_WEIGHT', 'UPPER', 'BICEPS'),
    ('HAMMERCURL',        '해머 컬',                'FREE_WEIGHT', 'UPPER', 'BICEPS'),
    ('PREACHERCURL',      '프리처 컬',              'MACHINE',     'UPPER', 'BICEPS'),
    ('CABLECURL',         '케이블 컬',              'MACHINE',     'UPPER', 'BICEPS'),
    ('TRICEPSPUSHDOWN',   '트라이셉스 푸시다운',    'MACHINE',     'UPPER', 'TRICEPS'),
    ('SKULLCRUSHER',      '스컬 크러셔',            'FREE_WEIGHT', 'UPPER', 'TRICEPS'),
    ('DUMBBELLKICKBACK',  '덤벨 킥백',              'FREE_WEIGHT', 'UPPER', 'TRICEPS'),
    ('OVERHEADTRICEPSEXTENSION', '오버헤드 트라이셉스 익스텐션', 'FREE_WEIGHT', 'UPPER', 'TRICEPS'),
    ('ASSISTEDDIP',       '어시스트 딥',            'MACHINE',     'UPPER', 'TRICEPS'),
    ('SQUAT',             '스쿼트',                 'FREE_WEIGHT', 'LOWER', 'QUADS'),
    ('FRONTSQUAT',        '프론트 스쿼트',          'FREE_WEIGHT', 'LOWER', 'QUADS'),
    ('GOBLETSQUAT',       '고블릿 스쿼트',          'FREE_WEIGHT', 'LOWER', 'QUADS'),
    ('BULGARIANSPLITSQUAT','불가리안 스플릿 스쿼트','FREE_WEIGHT', 'LOWER', 'QUADS'),
    ('WALKINGLUNGE',      '워킹 런지',              'FREE_WEIGHT', 'LOWER', 'QUADS'),
    ('DEADLIFT',          '데드리프트',             'FREE_WEIGHT', 'LOWER', 'GLUTES'),
    ('SUMODEADLIFT',      '스모 데드리프트',        'FREE_WEIGHT', 'LOWER', 'GLUTES'),
    ('ROMANIANDEADLIFT',  '루마니안 데드리프트',    'FREE_WEIGHT', 'LOWER', 'HAMSTRINGS'),
    ('GOODMORNING',       '굿모닝',                 'FREE_WEIGHT', 'LOWER', 'HAMSTRINGS'),
    ('HIPTHRUST',         '힙 스러스트',            'FREE_WEIGHT', 'LOWER', 'GLUTES'),
    ('LEGPRESS',          '레그프레스',             'MACHINE',     'LOWER', 'QUADS'),
    ('HACKSQUAT',         '핵 스쿼트',              'MACHINE',     'LOWER', 'QUADS'),
    ('LEGEXTENSION',      '레그 익스텐션',          'MACHINE',     'LOWER', 'QUADS'),
    ('LEGCURL',           '레그 컬',                'MACHINE',     'LOWER', 'HAMSTRINGS'),
    ('LYINGLEGCURL',      '라잉 레그 컬',           'MACHINE',     'LOWER', 'HAMSTRINGS'),
    ('SEATEDLEGCURL',     '시티드 레그 컬',         'MACHINE',     'LOWER', 'HAMSTRINGS'),
    ('CALFRAISE',         '카프 레이즈',            'MACHINE',     'LOWER', 'CALVES'),
    ('STANDINGCALFRAISE', '스탠딩 카프 레이즈',    'MACHINE',     'LOWER', 'CALVES')
ON DUPLICATE KEY UPDATE
    `training_display_name` = VALUES(`training_display_name`),
    `training_type` = VALUES(`training_type`),
    `target_category` = VALUES(`target_category`),
    `target_muscle` = VALUES(`target_muscle`);
